// Sample news data for the prototype
export interface NewsStory {
  id: string;
  title: string;
  category: 'sport' | 'economie' | 'klimaat' | 'opmerkelijk' | 'politiek' | 'cultuur' | 'rechtspraak' | 'tech';
  country: string;
  region: string;
  coordinates: [number, number]; // [longitude, latitude]
  imageUrl: string;
  summary: string;
  fullText?: string; // Optional full article text
  date: string;
}

export const newsStories: NewsStory[] = [
  {
    id: '1',
    title: 'Paus roept op tot vrijlating journalisten bij eerste ontmoeting met pers',
    category: 'politiek',
    country: 'Vatican',
    region: 'Europe',
    coordinates: [12.45, 41.9],
    imageUrl: '/placeholder.svg',
    summary: 'Paus Franciscus heeft opgeroepen tot de vrijlating van journalisten wereldwijd tijdens zijn eerste persontmoeting als nieuwe paus.',
    fullText: 'Tijdens zijn eerste formele ontmoeting met duizenden journalisten van over de hele wereld, benadrukte Paus Franciscus het belang van een vrije en onafhankelijke pers. Hij sprak zijn zorgen uit over journalisten die gevangen zitten of onderdrukt worden vanwege hun werk en riep regeringen op hun rechten te respecteren. \n\nDe paus bedankte de media ook voor hun werk tijdens het conclaaf en vroeg om begrip voor de uitdagingen van zijn nieuwe rol. Hij sloot af met een zegen voor alle aanwezigen en hun families.',
    date: '2023-05-12',
  },
  {
    id: '2',
    title: 'VN-voedselwaarschuwing: iedereen in Gaza riskeert hongersnood',
    category: 'politiek',
    country: 'Palestine',
    region: 'Middle East',
    coordinates: [34.3, 31.4],
    imageUrl: '/placeholder.svg',
    summary: 'De Verenigde Naties waarschuwen dat de gehele bevolking van Gaza hongersnood riskeert door aanhoudende conflicten en blokkades.',
    fullText: 'De situatie in Gaza is kritiek, aldus de VN-rapporteur. Door de aanhoudende blokkades en recente escalaties is de toegang tot voedsel, water en medische hulp ernstig beperkt. \n\nHulporganisaties proberen noodhulp te bieden, maar de omvang van de crisis overstijgt de huidige capaciteit. Er is dringend internationale actie nodig om een humanitaire ramp af te wenden en duurzame oplossingen te vinden.',
    date: '2023-05-10',
  },
  {
    id: '3',
    title: 'Polen sluit Russisch consulaat als straf voor brand winkelcentrum',
    category: 'politiek',
    country: 'Poland',
    region: 'Europe',
    coordinates: [19.12, 52.22],
    imageUrl: '/placeholder.svg',
    summary: 'Polen heeft besloten het Russische consulaat te sluiten als reactie op een brand in een winkelcentrum die aan Rusland wordt toegeschreven.',
    date: '2023-05-09',
  },
  {
    id: '4',
    title: 'Dankzij AI is leider Burkina Faso een hype op social media: "Hij heeft de vibe"',
    category: 'tech',
    country: 'Burkina Faso',
    region: 'Africa',
    coordinates: [-1.56, 12.36],
    imageUrl: '/placeholder.svg',
    summary: 'De leider van Burkina Faso is viral gegaan op sociale media dankzij AI-gegenereerde content die zijn charisma benadrukt.',
    date: '2023-05-08',
  },
  {
    id: '5',
    title: 'Recordtemperaturen gemeten in Zuidelijke Oceaan door klimaatverandering',
    category: 'klimaat',
    country: 'Antarctica',
    region: 'Antarctica',
    coordinates: [0, -70],
    imageUrl: '/placeholder.svg',
    summary: 'Wetenschappers hebben alarmerende recordtemperaturen gemeten in de Zuidelijke Oceaan, met mogelijke gevolgen voor zeespiegelstijging.',
    fullText: 'Metingen van onderzoeksschepen en satellieten tonen een ongekende opwarming van het oppervlaktewater rond Antarctica. Deze trend, direct gelinkt aan de wereldwijde klimaatverandering, bedreigt het delicate ecosysteem en versnelt het smelten van ijskappen. \n\nExperts waarschuwen voor de langetermijneffecten op de zeespiegel en het wereldwijde klimaatpatroon als deze trend doorzet. Het benadrukt de urgentie van internationale klimaatakkoorden.',
    date: '2023-05-11',
  },
  {
    id: '6',
    title: 'Europese economie toont veerkracht ondanks inflatiedruk',
    category: 'economie',
    country: 'European Union',
    region: 'Europe',
    coordinates: [9.14, 48.52],
    imageUrl: '/placeholder.svg',
    summary: 'De Europese economie blijkt veerkrachtig te zijn ondanks aanhoudende inflatiedruk en geopolitieke spanningen.',
    date: '2023-05-07',
  },
  {
    id: '7',
    title: 'Nieuw festival viert culturele diversiteit in Aziatische gemeenschappen',
    category: 'cultuur',
    country: 'Japan',
    region: 'Asia',
    coordinates: [139.83, 35.65],
    imageUrl: '/placeholder.svg',
    summary: 'Een nieuw internationaal festival brengt diverse Aziatische culturele tradities samen in een maand van vieringen en uitwisselingen.',
    fullText: "Het 'Asian Cultures Connect' festival, dat plaatsvindt in Tokio, biedt een platform voor artiesten, muzikanten en chefs uit heel Azië. Bezoekers kunnen genieten van traditionele dansoptredens, hedendaagse kunstinstallaties en culinaire workshops. \n\nHet doel is om begrip en waardering voor de rijke culturele diversiteit van het continent te bevorderen en interculturele dialoog te stimuleren, aldus de organisatoren.",
    date: '2023-05-06',
  },
  {
    id: '8',
    title: 'Doorbraak in kwantumcomputing bereikt door internationale samenwerking',
    category: 'tech',
    country: 'United States',
    region: 'North America',
    coordinates: [-122.33, 47.61],
    imageUrl: '/placeholder.svg',
    summary: 'Een internationaal team van wetenschappers heeft een significante doorbraak bereikt in kwantumcomputing door een nieuw type qubit te ontwikkelen.',
    date: '2023-05-05',
  },
  {
    id: '17',
    title: 'Eerste vrouwelijke president verkozen in Senegal',
    category: 'politiek',
    country: 'Senegal',
    region: 'Africa',
    coordinates: [-17.44, 14.69],
    imageUrl: '/placeholder.svg',
    summary: 'In een historische verkiezing is de eerste vrouwelijke president van Senegal verkozen, wat wereldwijd wordt geprezen als een doorbraak in gendergelijkheid.',
    date: '2023-04-26',
  },
  {
    id: '18',
    title: "Internationale markt voor elektrische auto's groeit explosief",
    category: 'economie',
    country: 'Germany',
    region: 'Europe',
    coordinates: [13.40, 52.52],
    imageUrl: '/placeholder.svg',
    summary: "De verkoop van elektrische auto's is wereldwijd met 30% gestegen, met Duitsland als een van de grootste markten.",
    date: '2023-04-25',
  },
  {
    id: '19',
    title: 'Aardbeving treft noordelijk Iran, honderden gewonden gemeld',
    category: 'klimaat',
    country: 'Iran',
    region: 'Middle East',
    coordinates: [51.38, 35.68],
    imageUrl: '/placeholder.svg',
    summary: 'Een aardbeving met een kracht van 6.1 op de schaal van Richter heeft het noorden van Iran getroffen, met schade aan infrastructuur en honderden gewonden.',
    date: '2023-04-24',
  },
  {
    id: '20',
    title: 'Wereldwijd onderzoek gestart naar ethiek van gezichtsherkenning',
    category: 'tech',
    country: 'Sweden',
    region: 'Europe',
    coordinates: [18.06, 59.33],
    imageUrl: '/placeholder.svg',
    summary: 'Onder leiding van Zweedse onderzoekers is een wereldwijd onderzoek gestart naar de ethische implicaties van gezichtsherkenningstechnologie.',
    date: '2023-04-23',
  },
  {
    id: '21',
    title: 'Nieuwe culturele hotspot opent in hartje Cairo',
    category: 'cultuur',
    country: 'Egypt',
    region: 'Africa',
    coordinates: [31.23, 30.04],
    imageUrl: '/placeholder.svg',
    summary: 'In Cairo is een moderne culturele hub geopend die kunst, muziek en educatie samenbrengt, met als doel jongeren aan te moedigen hun creativiteit te ontwikkelen.',
    date: '2023-04-22',
  },
  {
    id: '22',
    title: 'Noorse wetenschappers ontdekken mogelijke remedie tegen zeldzame zenuwziekte',
    category: 'tech',
    country: 'Norway',
    region: 'Europe',
    coordinates: [10.75, 59.91],
    imageUrl: '/placeholder.svg',
    summary: 'Een onderzoeksteam in Noorwegen heeft een potentieel medicijn ontwikkeld voor een zeldzame genetische zenuwziekte, dat nu klinisch getest wordt.',
    date: '2023-04-21',
  },
  {
    id: '23',
    title: 'India lanceert grootste hernieuwbare energieproject ooit',
    category: 'klimaat',
    country: 'India',
    region: 'Asia',
    coordinates: [77.21, 28.61],
    imageUrl: '/placeholder.svg',
    summary: 'India investeert miljarden in een nieuw zonne- en windenergieproject in de Tharwoestijn, met als doel de uitstoot drastisch te verlagen.',
    date: '2023-04-20',
  },
  {
    id: '24',
    title: 'Economisch herstel in Argentinië blijft fragiel ondanks IMF-steun',
    category: 'economie',
    country: 'Argentina',
    region: 'South America',
    coordinates: [-58.42, -34.61],
    imageUrl: '/placeholder.svg',
    summary: 'Ondanks financiële steun van het IMF blijft het economische herstel in Argentinië onzeker, met hoge inflatie en beperkte koopkracht.',
    date: '2023-04-19',
  },
  {
    id: '9',
    title: 'Zuid-Koreaanse jongeren protesteren tegen werkdruk en onderwijssysteem',
    category: 'cultuur',
    country: 'South Korea',
    region: 'Asia',
    coordinates: [126.98, 37.56],
    imageUrl: '/placeholder.svg',
    summary: 'Duizenden Zuid-Koreaanse jongeren gingen de straat op in Seoul om te protesteren tegen de hoge werkdruk en prestatiedruk binnen het onderwijs.',
    date: '2023-05-04',
  },
  {
    id: '10',
    title: 'Nederland kondigt nieuwe windparken op Noordzee aan',
    category: 'klimaat',
    country: 'Netherlands',
    region: 'Europe',
    coordinates: [4.90, 52.37],
    imageUrl: '/placeholder.svg',
    summary: 'De Nederlandse regering investeert in meerdere nieuwe windparken op de Noordzee om de energietransitie te versnellen.',
    date: '2023-05-03',
  },
  {
    id: '11',
    title: 'Historische vredesdeal bereikt tussen Colombiaanse regering en rebellen',
    category: 'politiek',
    country: 'Colombia',
    region: 'South America',
    coordinates: [-74.07, 4.61],
    imageUrl: '/placeholder.svg',
    summary: 'Na jaren van conflict hebben de Colombiaanse regering en rebellen een historische vredesovereenkomst getekend in Bogotá.',
    date: '2023-05-02',
  },
  {
    id: '12',
    title: 'Dreigende droogte in Australië zet landbouwsector onder druk',
    category: 'klimaat',
    country: 'Australia',
    region: 'Oceania',
    coordinates: [149.13, -35.28],
    imageUrl: '/placeholder.svg',
    summary: 'Een toenemende droogte in Australië leidt tot zorgen binnen de landbouwsector over oogstverliezen en voedselvoorziening.',
    date: '2023-05-01',
  },
  {
    id: '13',
    title: 'Toerisme in Marokko herstelt snel na pandemie',
    category: 'economie',
    country: 'Morocco',
    region: 'Africa',
    coordinates: [-6.84, 34.02],
    imageUrl: '/placeholder.svg',
    summary: 'De toeristische sector in Marokko laat een sterk herstel zien na de pandemie, met een recordaantal internationale bezoekers.',
    date: '2023-04-30',
  },
  {
    id: '14',
    title: 'Nieuwe AI-wetgeving in Canada roept vragen op bij techbedrijven',
    category: 'tech',
    country: 'Canada',
    region: 'North America',
    coordinates: [-75.69, 45.42],
    imageUrl: '/placeholder.svg',
    summary: 'Canada stelt nieuwe regelgeving voor rondom het gebruik van AI, wat leidt tot bezorgdheid bij technologiebedrijven over innovatiebeperkingen.',
    date: '2023-04-29',
  },
  {
    id: '15',
    title: 'Internationale dansdag gevierd met optredens in 40 landen',
    category: 'cultuur',
    country: 'Brazil',
    region: 'South America',
    coordinates: [-43.17, -22.91],
    imageUrl: '/placeholder.svg',
    summary: 'Op Internationale Dansdag kwamen artiesten wereldwijd samen om via dans culturele expressie en verbondenheid te vieren.',
    date: '2023-04-28',
  },
  {
    id: '16',
    title: 'Techgigant lanceert satellietnetwerk voor internet in afgelegen gebieden',
    category: 'tech',
    country: 'China',
    region: 'Asia',
    coordinates: [116.40, 39.90],
    imageUrl: '/placeholder.svg',
    summary: 'Een Chinees technologiebedrijf heeft een wereldwijd satellietnetwerk gelanceerd om internettoegang in afgelegen gebieden te verbeteren.',
    date: '2023-04-27',
  },{
    id: '51',
    title: 'VN-top bespreekt gevolgen van smeltende gletsjers in Himalaya',
    category: 'klimaat',
    country: 'Nepal',
    region: 'Asia',
    coordinates: [85.32, 27.71],
    imageUrl: '/placeholder.svg',
    summary: 'Tijdens een VN-conferentie in Kathmandu werden zorgen geuit over de versnelde smelting van gletsjers en de gevolgen voor miljoenen mensen in de regio.',
    date: '2023-04-18',
  },
  {
    id: '52',
    title: 'België voert extra belasting in op digitale diensten',
    category: 'economie',
    country: 'Belgium',
    region: 'Europe',
    coordinates: [4.35, 50.85],
    imageUrl: '/placeholder.svg',
    summary: 'De Belgische regering voert een nieuwe belasting in op grote techbedrijven die digitale diensten aanbieden binnen het land.',
    date: '2023-04-17',
  },
  {
    id: '53',
    title: 'Nieuwe kunstmatige intelligentie schrijft poëzie in lokale dialecten',
    category: 'tech',
    country: 'Ireland',
    region: 'Europe',
    coordinates: [-6.26, 53.35],
    imageUrl: '/placeholder.svg',
    summary: 'Een Iers onderzoekscentrum heeft een AI ontwikkeld die poëzie kan genereren in meerdere Ierse dialecten, wat gezien wordt als een stap richting cultuurbehoud.',
    date: '2023-04-16',
  },
  {
    id: '54',
    title: 'Vrouwenteam uit Afghanistan wint internationale sportprijs',
    category: 'sport',
    country: 'Afghanistan',
    region: 'Asia',
    coordinates: [69.17, 34.53],
    imageUrl: '/placeholder.svg',
    summary: 'Een Afghaans vrouwenteam is internationaal onderscheiden voor hun doorzettingsvermogen en prestaties in de sportwereld ondanks moeilijke omstandigheden.',
    date: '2023-04-15',
  },
  {
    id: '55',
    title: 'Zuid-Soedan plant grootste herbebossingsproject ooit in regio',
    category: 'klimaat',
    country: 'South Sudan',
    region: 'Africa',
    coordinates: [31.58, 4.85],
    imageUrl: '/placeholder.svg',
    summary: 'Zuid-Soedan start met het planten van miljoenen bomen in een poging om landdegradatie en droogte tegen te gaan.',
    date: '2023-04-14',
  },
  {
    id: '56',
    title: 'Estland digitaliseert volledige gezondheidszorgsysteem',
    category: 'tech',
    country: 'Estonia',
    region: 'Europe',
    coordinates: [24.75, 59.44],
    imageUrl: '/placeholder.svg',
    summary: 'Estland loopt voorop in digitalisering en heeft nu het volledige gezondheidszorgsysteem gedigitaliseerd, inclusief patiëntendossiers.',
    date: '2023-03-09',
  },
  {
    id: '57',
    title: 'Internationale kritiek op gevangenisomstandigheden in Venezuela',
    category: 'politiek',
    country: 'Venezuela',
    region: 'South America',
    coordinates: [-66.90, 10.49],
    imageUrl: '/placeholder.svg',
    summary: 'Mensenrechtenorganisaties luiden de noodklok over de mensonterende omstandigheden in Venezolaanse gevangenissen.',
    date: '2023-04-12',
  },
  {
    id: '58',
    title: 'Vergeten talen herleven via virtual reality in Bolivia',
    category: 'cultuur',
    country: 'Bolivia',
    region: 'South America',
    coordinates: [-68.12, -16.5],
    imageUrl: '/placeholder.svg',
    summary: 'Een Boliviaans museum gebruikt VR-technologie om bezoekers onder te dompelen in uitgestorven talen en culturen van de Andes.',
    date: '2023-04-11',
  },
  {
    id: '59',
    title: 'Nieuw vaccin tegen dengue getest in Maleisië',
    category: 'tech',
    country: 'Malaysia',
    region: 'Asia',
    coordinates: [101.69, 3.14],
    imageUrl: '/placeholder.svg',
    summary: 'Wetenschappers in Maleisië testen een nieuw vaccin tegen dengue, een virus dat jaarlijks miljoenen treft in tropische gebieden.',
    date: '2023-04-10',
  },
  {
    id: '60',
    title: 'Zwitserland organiseert referendum over AI-regulering',
    category: 'politiek',
    country: 'Switzerland',
    region: 'Europe',
    coordinates: [8.54, 47.37],
    imageUrl: '/placeholder.svg',
    summary: 'Zwitserland houdt een nationaal referendum over de regulering van kunstmatige intelligentie, waarbij privacy en transparantie centraal staan.',
    date: '2023-04-09',
  },
  

];

export const categories = [
  { id: "sport", name: "Sport", className: "bg-orange-500 hover:bg-orange-600 text-white" },
  { id: "economie", name: "Economie", className: "bg-blue-500 hover:bg-blue-600 text-white" },
  { id: "klimaat", name: "Klimaat", className: "bg-green-500 hover:bg-green-600 text-white" },
  { id: "opmerkelijk", name: "Opmerkelijk", className: "bg-pink-500 hover:bg-pink-600 text-white" },
  { id: "politiek", name: "Politiek", className: "bg-red-500 hover:bg-red-600 text-white" },
  { id: "cultuur", name: "Cultuur", className: "bg-yellow-500 hover:bg-yellow-600 text-white" },
  { id: "rechtspraak", name: "Rechtspraak", className: "bg-gray-200 hover:bg-gray-300 text-black" },
  { id: "tech", name: "Tech", className: "bg-gray-500 hover:bg-gray-600 text-white" },
];

export const getStoriesByCategory = (categoryId: string | null) => {
  if (!categoryId) return newsStories;
  return newsStories.filter(story => story.category === categoryId);
};

export const getStoriesBySearch = (query: string) => {
  const lowerCaseQuery = query.toLowerCase();
  return newsStories.filter(
    story => 
      story.title.toLowerCase().includes(lowerCaseQuery) || 
      story.country.toLowerCase().includes(lowerCaseQuery) ||
      story.summary.toLowerCase().includes(lowerCaseQuery)
  );
};
